
name: FitFinder CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v2
        with:
          xcode-version: '14.0'
      - name: Run Tests
        run: swift test
 
